// Common game providers
export const COMMON_GAME_PROVIDERS = [
  'NetEnt',
  'Evolution',
  'Pragmatic Play',
  'Push Gaming',
  'Red Tiger',
  'Microgaming',
  'Nolimit City',
  'Big Time Gaming',
  'Spinomenal',
  'Playson',
  'BF Games',
  'HackSaw',
  'Red Rake',
  'BetSoft',
  'Iron Dog',
  'OneTouch',
  '1x2gaming',
  'JFTW',
  'BGaming',
  'Swintt',
  'Casino Technology',
  'Gamesburger Studios',
  'Endorphina',
  'Tom Horn',
  'Platipus',
  'All41 Studios',
  'Felix Gaming',
  'PariPlay',
  'Fugaso',
  'SmartSoft',
  'Foxium',
  'Mascot',
  'Leap',
  'Caleta',
  'Stormcraft Studios',
  'Triple Edge Studios',
  'SlotVision',
  'Salsa Technology',
  'Rabacat',
  'Switch Studios',
  'Real Dealer Studios',
  'Kiron',
  'Woohoo Games',
  'BetGames',
  'Golden Rock Studios',
  '2By2',
  'Horse Racing',
  'Fantasma',
  'ELK',
  'Claw',
  'Play\'n GO',
  'Yggdrasil',
  'Quickspin',
  'Thunderkick',
  'Relax Gaming',
  'Blueprint Gaming',
  'IGT',
  'WMS',
  'Bally',
  'Novomatic',
  'Greentube',
  'Amatic',
  'Belatra',
  'GameArt',
  'Habanero',
  'Merkur',
  'MrSlotty',
  'ReelPlay',
  'Reel Time Gaming',
  'Spadegaming',
  'TrueLab Games',
  'Wazdan',
];

