// Common languages used in casinos
export const COMMON_LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Dutch',
  'Russian',
  'Polish',
  'Swedish',
  'Norwegian',
  'Finnish',
  'Danish',
  'Greek',
  'Hungarian',
  'Czech',
  'Romanian',
  'Turkish',
  'Arabic',
  'Japanese',
  'Chinese',
  'Korean',
  'Hindi',
  'Thai',
  'Vietnamese',
  'Indonesian',
  'Malay',
  'Filipino',
  'Hebrew',
  'Ukrainian',
  'Bulgarian',
  'Croatian',
  'Serbian',
  'Slovak',
  'Slovenian',
  'Estonian',
  'Latvian',
  'Lithuanian',
];

export const LANGUAGE_CODES: Record<string, string> = {
  'English': 'EN',
  'Spanish': 'ES',
  'French': 'FR',
  'German': 'DE',
  'Italian': 'IT',
  'Portuguese': 'PT',
  'Dutch': 'NL',
  'Russian': 'RU',
  'Polish': 'PL',
  'Swedish': 'SV',
  'Norwegian': 'NO',
  'Finnish': 'FI',
  'Danish': 'DA',
  'Greek': 'EL',
  'Hungarian': 'HU',
  'Czech': 'CS',
  'Romanian': 'RO',
  'Turkish': 'TR',
  'Arabic': 'AR',
  'Japanese': 'JA',
  'Chinese': 'ZH',
  'Korean': 'KO',
  'Hindi': 'HI',
  'Thai': 'TH',
  'Vietnamese': 'VI',
  'Indonesian': 'ID',
  'Malay': 'MS',
  'Filipino': 'FIL',
  'Hebrew': 'HE',
  'Ukrainian': 'UK',
  'Bulgarian': 'BG',
  'Croatian': 'HR',
  'Serbian': 'SR',
  'Slovak': 'SK',
  'Slovenian': 'SL',
  'Estonian': 'ET',
  'Latvian': 'LV',
  'Lithuanian': 'LT',
};

