import type { Casino } from '../models/casino.model';

// Mock casino data matching the design
export const mockCasinos: Casino[] = [
  {
    _id: '1',
    name: 'Onedun Casino',
    logo: 'https://s3-eu-west-1.amazonaws.com/tpd/logos/64411c6462eb9c64aaae6028/0x0.png',
    image: 'https://images.unsplash.com/photo-1530533718754-001d2668365a?w=800&h=600&fit=crop',
    safetyIndex: 8.3,
    countryCode: 'MT',
    countryFlag: '🇲🇹',
    features: [
      { type: 'positive', text: 'Small international casino' },
      { type: 'positive', text: 'Wide range of bonuses both for new and loyal players' },
      { type: 'positive', text: 'Deposits and withdrawals via cryptocurrencies' },
      { type: 'negative', text: 'Not all game providers are available for all countries' },
    ],
    bonusText: '150% up to €1,500 and 150 extra spins (€0.1/spin)',
    bonusSubtext: 'T&Cs apply',
    isExclusive: true,
    websiteLanguages: ['English', 'German', 'French', 'Spanish', 'Italian', 'Portuguese', 'Dutch', 'Finnish'],
    liveChatLanguages: ['English', 'German'],
    customerSupportLanguages: ['English'],
    availableGames: [
      { name: 'Slots', available: true },
      { name: 'Roulette', available: true },
      { name: 'Blackjack', available: true },
      { name: 'No betting', available: false },
      { name: 'Video poker', available: true },
      { name: 'Bingo', available: true },
      { name: 'Live games', available: true },
      { name: 'Baccarat', available: true },
      { name: 'Craps and dice', available: true },
      { name: 'Scratch cards', available: true },
      { name: 'Crash games', available: true },
      { name: 'Jackpot games', available: true },
      { name: 'Keno', available: true },
    ],
    paymentMethods: [
      { name: 'Neteller' },
      { name: 'PaysafeCard' },
      { name: 'Mastercard' },
      { name: 'Skrill' },
      { name: 'Payz' },
      { name: 'POLi' },
      { name: 'Multibanco' },
      { name: 'Nordea' },
      { name: 'Bitcoin' },
      { name: 'Ethereum' },
      { name: 'Litecoin' },
      { name: 'Bank Transfer' },
      // ... and more (93 total in the design)
    ],
    visitUrl: 'https://example.com/onedun',
    reviewUrl: 'https://example.com/review/onedun',
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    _id: '2',
    name: 'irwin Casino',
    logo: 'https://yt3.googleusercontent.com/jzqKeKuso3zfOTytZIPhzwmlJNt0wlWyWQQt99YNeBJHsQOzxXocJNH1uIUA-Pznz9Ij9ji4KA=s900-c-k-c0x00ffffff-no-rj',
    image: 'https://images.unsplash.com/photo-1511882150382-421056c89033?w=800&h=600&fit=crop',
    safetyIndex: 8.2,
    countryCode: 'CU',
    countryFlag: '🇨🇺',
    features: [
      { type: 'neutral', text: 'The daily withdrawal limit depends on the player\'s status' },
      { type: 'positive', text: 'Deposits and withdrawals via cryptocurrencies' },
      { type: 'positive', text: 'Various responsible gaming options available' },
      { type: 'negative', text: 'Fees for some deposit and withdrawal methods' },
    ],
    bonusText: '50% up to €300',
    bonusSubtext: 'T&Cs apply',
    isExclusive: false,
    websiteLanguages: ['English', 'German', 'Spanish'],
    liveChatLanguages: ['English'],
    customerSupportLanguages: ['English'],
    availableGames: [
      { name: 'Slots', available: true },
      { name: 'Roulette', available: true },
      { name: 'Blackjack', available: true },
      { name: 'Betting', available: true },
      { name: 'Video poker', available: true },
      { name: 'Bingo', available: true },
      { name: 'Live games', available: true },
      { name: 'Baccarat', available: true },
      { name: 'Jackpot games', available: true },
    ],
    paymentMethods: [
      { name: 'Mastercard' },
      { name: 'Visa' },
      { name: 'Skrill' },
      { name: 'Neteller' },
      { name: 'Bitcoin' },
      { name: 'Bank Transfer' },
      // ... and more (30 total in the design)
    ],
    visitUrl: 'https://example.com/irwin',
    reviewUrl: 'https://example.com/review/irwin',
    createdAt: new Date('2024-03-10').toISOString(),
  },
  {
    _id: '3',
    name: 'SpinBetter Casino',
    logo: 'https://yt3.googleusercontent.com/ytc/AIdro_knWLBI_HCQVf3ePiIQOI5UeTeVEFK9Yy6FNru2BruqGA=s900-c-k-c0x00ffffff-no-rj',
    image: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?w=800&h=600&fit=crop',
    safetyIndex: 8.5,
    countryCode: 'MT',
    countryFlag: '🇲🇹',
    features: [
      { type: 'positive', text: 'Large selection of slot games from top providers' },
      { type: 'positive', text: 'Fast withdrawal processing (24 hours)' },
      { type: 'positive', text: '24/7 customer support' },
      { type: 'positive', text: 'Mobile-optimized platform' },
    ],
    bonusText: '200% up to €2,000 + 100 free spins',
    bonusSubtext: 'T&Cs apply',
    isExclusive: true,
    websiteLanguages: ['English', 'German', 'French', 'Spanish', 'Italian', 'Norwegian'],
    liveChatLanguages: ['English', 'German', 'French'],
    customerSupportLanguages: ['English', 'German'],
    availableGames: [
      { name: 'Slots', available: true },
      { name: 'Roulette', available: true },
      { name: 'Blackjack', available: true },
      { name: 'Betting', available: true },
      { name: 'Video poker', available: true },
      { name: 'Bingo', available: true },
      { name: 'Live games', available: true },
      { name: 'Baccarat', available: true },
      { name: 'Craps and dice', available: true },
      { name: 'Scratch cards', available: true },
      { name: 'Jackpot games', available: true },
      { name: 'Keno', available: true },
      { name: 'Poker', available: true },
    ],
    paymentMethods: [
      { name: 'Visa' },
      { name: 'Mastercard' },
      { name: 'Skrill' },
      { name: 'Neteller' },
      { name: 'PayPal' },
      { name: 'Bitcoin' },
      { name: 'Ethereum' },
      { name: 'Bank Transfer' },
    ],
    visitUrl: 'https://example.com/spinbetter',
    reviewUrl: 'https://example.com/review/spinbetter',
    createdAt: new Date('2024-02-20').toISOString(),
  },
  {
    _id: '4',
    name: 'Royal Vegas Casino',
    logo: 'https://play-lh.googleusercontent.com/zrQA-ABgXk2A57_4iMs7kN9PcPJIBfaqLOy-A5pwoPIJNmgYq3EXMrDhsGzDnclLKqM',
    image: 'https://images.unsplash.com/photo-1590891839377-4b78f2d48bb6?w=800&h=600&fit=crop',
    safetyIndex: 7.8,
    countryCode: 'GB',
    countryFlag: '🇬🇧',
    features: [
      { type: 'positive', text: 'Established brand with excellent reputation' },
      { type: 'positive', text: 'Large game library with 500+ slots' },
      { type: 'neutral', text: 'Some payment methods have minimum deposit requirements' },
      { type: 'negative', text: 'Limited cryptocurrency options' },
    ],
    bonusText: '100% up to €500 welcome bonus',
    bonusSubtext: 'T&Cs apply',
    isExclusive: false,
    websiteLanguages: ['English', 'French', 'German', 'Spanish'],
    liveChatLanguages: ['English', 'French'],
    customerSupportLanguages: ['English'],
    availableGames: [
      { name: 'Slots', available: true },
      { name: 'Roulette', available: true },
      { name: 'Blackjack', available: true },
      { name: 'Betting', available: false },
      { name: 'Video poker', available: true },
      { name: 'Bingo', available: true },
      { name: 'Live games', available: true },
      { name: 'Baccarat', available: true },
    ],
    paymentMethods: [
      { name: 'Visa' },
      { name: 'Mastercard' },
      { name: 'Skrill' },
      { name: 'PayPal' },
      { name: 'Bank Transfer' },
    ],
    visitUrl: 'https://example.com/royalvegas',
    reviewUrl: 'https://example.com/review/royalvegas',
    createdAt: new Date('2023-12-05').toISOString(),
  },
  {
    _id: '5',
    name: 'Lucky Spin Casino',
    logo: 'https://www.lasvegas.ro/_next/image?url=%2Fimages%2Fplaceholder.webp&w=375&q=75',
    image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&h=600&fit=crop',
    safetyIndex: 8.0,
    countryCode: 'CY',
    countryFlag: '🇨🇾',
    features: [
      { type: 'positive', text: 'Newly launched with modern platform' },
      { type: 'positive', text: 'No deposit bonus available' },
      { type: 'positive', text: 'Extensive cryptocurrency support' },
      { type: 'neutral', text: 'Limited customer support languages' },
    ],
    bonusText: '€20 no deposit bonus + 200% up to €1,000',
    bonusSubtext: 'T&Cs apply',
    isExclusive: true,
    websiteLanguages: ['English', 'German', 'Spanish'],
    liveChatLanguages: ['English'],
    customerSupportLanguages: ['English'],
    availableGames: [
      { name: 'Slots', available: true },
      { name: 'Roulette', available: true },
      { name: 'Blackjack', available: true },
      { name: 'Video poker', available: true },
      { name: 'Live games', available: true },
      { name: 'Baccarat', available: true },
      { name: 'Jackpot games', available: true },
    ],
    paymentMethods: [
      { name: 'Bitcoin' },
      { name: 'Ethereum' },
      { name: 'Litecoin' },
      { name: 'Tether' },
      { name: 'Visa' },
      { name: 'Mastercard' },
    ],
    visitUrl: 'https://example.com/luckyspin',
    reviewUrl: 'https://example.com/review/luckyspin',
    createdAt: new Date('2024-04-01').toISOString(),
  },
];

