name: Debug Secret Content

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug Secret
        run: |
          echo "Secret length: ${#GCP_SA_KEY}"
          echo "First 200 characters:"
          echo "${{ secrets.GCP_SA_KEY }}" | head -c 200
          echo ""
          echo "Last 200 characters:"
          echo "${{ secrets.GCP_SA_KEY }}" | tail -c 200
          echo ""
          echo "Decoding base64 and checking JSON..."
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > test.json
          echo "Decoded JSON length: $(wc -c < test.json)"
          echo "First 200 chars of decoded JSON:"
          head -c 200 test.json
          echo ""
          echo "Last 200 chars of decoded JSON:"
          tail -c 200 test.json
          echo ""
          if jq empty test.json 2>/dev/null; then
            echo "✅ JSON is valid!"
          else
            echo "❌ JSON is invalid!"
          fi
