name: Debug Secret Content

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug Secret
        run: |
          echo "Secret length: ${#GCP_SA_KEY}"
          echo "First 200 characters:"
          echo "${{ secrets.GCP_SA_KEY }}" | head -c 200
          echo ""
          echo "Last 200 characters:"
          echo "${{ secrets.GCP_SA_KEY }}" | tail -c 200
          echo ""
          echo "Checking if JSON is valid..."
          echo "${{ secrets.GCP_SA_KEY }}" > test.json
          if jq empty test.json 2>/dev/null; then
            echo "✅ JSON is valid!"
          else
            echo "❌ JSON is invalid!"
            echo "First 1000 characters:"
            head -c 1000 test.json
          fi
