name: Debug Secret Content

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug Secret
        run: |
          echo "Secret length: ${#GCP_SA_KEY}"
          echo "First 100 characters:"
          echo "${{ secrets.GCP_SA_KEY }}" | head -c 100
          echo ""
          echo "Last 100 characters:"
          echo "${{ secrets.GCP_SA_KEY }}" | tail -c 100
          echo ""
          echo "Full secret (first 500 chars):"
          echo "${{ secrets.GCP_SA_KEY }}" | head -c 500
