name: Deploy Full Stack to Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-full:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      
      - name: Verify Authentication
        run: |
          echo "Checking authentication..."
          gcloud auth list
          echo "Current project:"
          gcloud config get-value project
      
      - name: Configure Docker
        run: gcloud auth configure-docker
      
      # Deploy Backend
      - name: Deploy Backend
        run: |
          echo "🚀 Deploying Backend..."
          cd server
          gcloud run deploy casino-offers-backend \
            --source . \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 3000 \
            --set-env-vars="NODE_ENV=production,APP_PORT=3000,APP_ENVIRONMENT=production"
      
      - name: Get Backend URL
        id: backend
        run: |
          BACKEND_URL=$(gcloud run services describe casino-offers-backend \
            --region us-central1 \
            --format 'value(status.url)')
          echo "url=$BACKEND_URL" >> $GITHUB_OUTPUT
          echo "✅ Backend deployed: $BACKEND_URL"
      
      # Deploy Frontend
      - name: Deploy Frontend
        run: |
          echo "🎨 Deploying Frontend..."
          gcloud run deploy casino-offers-frontend \
            --source . \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 3000 \
            --set-env-vars="NEXT_PUBLIC_API_URL=${{ steps.backend.outputs.url }}/api/v1"
      
      - name: Get Frontend URL
        id: frontend
        run: |
          FRONTEND_URL=$(gcloud run services describe casino-offers-frontend \
            --region us-central1 \
            --format 'value(status.url)')
          echo "url=$FRONTEND_URL" >> $GITHUB_OUTPUT
          echo "✅ Frontend deployed: $FRONTEND_URL"
      
      - name: Deployment Summary
        run: |
          echo "========================================="
          echo "✅ Deployment Complete!"
          echo "========================================="
          echo "Frontend: ${{ steps.frontend.outputs.url }}"
          echo "Backend: ${{ steps.backend.outputs.url }}"
          echo "========================================="

