name: Deploy Backend Only to GCP Cloud Run

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      - 'server/Dockerfile'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1
  BACKEND_SERVICE_NAME: casino-offers-backend

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    outputs:
      backend-url: ${{ steps.get-backend-url.outputs.url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          export_default_credentials: true
      
      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker
      
      - name: Build and Deploy Backend
        working-directory: ./server
        run: |
          echo "🚀 Building and deploying backend..."
          
          # Build and deploy to Cloud Run
          gcloud run deploy ${{ env.BACKEND_SERVICE_NAME }} \
            --source . \
            --platform managed \
            --region ${{ env.GCP_REGION }} \
            --allow-unauthenticated \
            --port 3000 \
            --memory 1Gi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 10 \
            --timeout 900 \
            --concurrency 100 \
            --set-env-vars="
              NODE_ENV=production,
              APP_PORT=3000,
              APP_ENVIRONMENT=production,
              APP_VERSIONING_DEFAULT_VERSION=v1,
              JWT_SECRET=${{ secrets.JWT_SECRET }},
              JWT_EXPIRES=${{ secrets.JWT_EXPIRES }},
              MONGO_DB_USER=${{ secrets.MONGO_DB_USER }},
              MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }},
              MONGO_DB_SERVER=${{ secrets.MONGO_DB_SERVER }},
              MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }},
              APP_NAME=Casino Offers API,
              APP_SWAGGER_TAG=casino-offers,
              APP_SWAGGER_VERSION=1.0.0,
              APP_SWAGGER_SERVER=https://${{ env.BACKEND_SERVICE_NAME }}-${{ env.GCP_PROJECT_ID }}.a.run.app
            " \
            --quiet
          
          echo "✅ Backend deployment completed!"
      
      - name: Wait for Backend to be Ready
        run: |
          echo "⏳ Waiting for backend service to be ready..."
          sleep 30
          
          # Get the service URL
          BACKEND_URL=$(gcloud run services describe ${{ env.BACKEND_SERVICE_NAME }} \
            --region ${{ env.GCP_REGION }} \
            --format 'value(status.url)')
          
          echo "Backend URL: $BACKEND_URL"
          
          # Wait for health check
          for i in {1..10}; do
            if curl -f "$BACKEND_URL/health" > /dev/null 2>&1; then
              echo "✅ Backend is healthy!"
              break
            else
              echo "⏳ Backend not ready yet, waiting... (attempt $i/10)"
              sleep 10
            fi
          done
      
      - name: Get Backend URL
        id: get-backend-url
        run: |
          BACKEND_URL=$(gcloud run services describe ${{ env.BACKEND_SERVICE_NAME }} \
            --region ${{ env.GCP_REGION }} \
            --format 'value(status.url)')
          echo "url=$BACKEND_URL" >> $GITHUB_OUTPUT
          echo "Backend URL: $BACKEND_URL"
      
      - name: Test Backend API
        run: |
          BACKEND_URL="${{ steps.get-backend-url.outputs.url }}"
          echo "🧪 Testing backend API..."
          
          # Test health endpoint
          curl -f "$BACKEND_URL/health" || exit 1
          
          # Test API endpoint
          curl -f "$BACKEND_URL/api/v1" || echo "⚠️ API endpoint not ready yet"
          
          echo "✅ Backend API tests passed!"
      
      - name: Summary
        run: |
          echo "========================================="
          echo "🚀 Backend Deployment Complete!"
          echo "========================================="
          echo "Backend URL: ${{ steps.get-backend-url.outputs.url }}"
          echo "========================================="
