name: Deploy to GCP Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      
      - name: Verify Authentication
        run: gcloud auth list
      
      - name: Configure Docker
        run: gcloud auth configure-docker
      
      - name: Deploy Backend to Cloud Run
        run: |
          cd server
          gcloud run deploy casino-offers-backend \
            --source . \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port 3000 \
            --set-env-vars="NODE_ENV=production,APP_PORT=3000,APP_ENVIRONMENT=production"
      
      - name: Get Backend URL
        id: backend-url
        run: |
          BACKEND_URL=$(gcloud run services describe casino-offers-backend --region ${{ env.REGION }} --format 'value(status.url)')
          echo "url=$BACKEND_URL" >> $GITHUB_OUTPUT
          echo "Backend deployed at: $BACKEND_URL"

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: deploy-backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      
      - name: Verify Authentication
        run: gcloud auth list
      
      - name: Configure Docker
        run: gcloud auth configure-docker
      
      - name: Deploy Frontend to Cloud Run
        run: |
          BACKEND_URL=$(gcloud run services describe casino-offers-backend --region ${{ env.REGION }} --format 'value(status.url)')
          gcloud run deploy casino-offers-frontend \
            --source . \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port 3000 \
            --set-env-vars="NEXT_PUBLIC_API_URL=$BACKEND_URL/api/v1"
      
      - name: Get Frontend URL
        run: |
          FRONTEND_URL=$(gcloud run services describe casino-offers-frontend --region ${{ env.REGION }} --format 'value(status.url)')
          echo "Frontend deployed at: $FRONTEND_URL"
          echo "Backend URL: $(gcloud run services describe casino-offers-backend --region ${{ env.REGION }} --format 'value(status.url)')"

  notify:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    if: always()
    
    steps:
      - name: Deployment Summary
        run: |
          echo "🚀 Deployment completed!"
          echo "Frontend: $(gcloud run services describe casino-offers-frontend --region ${{ env.REGION }} --format 'value(status.url)')"
          echo "Backend: $(gcloud run services describe casino-offers-backend --region ${{ env.REGION }} --format 'value(status.url)')"
