name: Test GCP Authentication

on:
  workflow_dispatch:

jobs:
  test-auth:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      
      - name: Test Authentication
        run: |
          echo "Testing authentication..."
          gcloud auth list
          echo "Current project:"
          gcloud config get-value project
          echo "Testing gcloud command:"
          gcloud projects describe ${{ secrets.GCP_PROJECT_ID }}
