name: Test GCP Authentication

on:
  workflow_dispatch:

jobs:
  test-auth:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Debug Secrets
        run: |
          echo "Checking if secrets exist..."
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "❌ GCP_SA_KEY secret is not set or empty"
          else
            echo "✅ GCP_SA_KEY secret exists (length: ${#GCP_SA_KEY})"
          fi
          
          if [ -z "${{ secrets.GCP_PROJECT_ID }}" ]; then
            echo "❌ GCP_PROJECT_ID secret is not set or empty"
          else
            echo "✅ GCP_PROJECT_ID secret exists: ${{ secrets.GCP_PROJECT_ID }}"
          fi
      
      - name: Manual Authentication
        run: |
          echo "Creating service account key file..."
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-sa-key.json
          echo "File created, checking content..."
          head -c 100 gcp-sa-key.json
          echo ""
          echo "Authenticating..."
          gcloud auth activate-service-account --key-file=gcp-sa-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Test Authentication
        run: |
          echo "Testing authentication..."
          gcloud auth list
          echo "Current project:"
          gcloud config get-value project
          echo "Testing gcloud command:"
          gcloud projects describe ${{ secrets.GCP_PROJECT_ID }}
